# Generated by Django 2.2.2 on 2019-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_choice_question_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(),
        ),
    ]
