# Generated by Django 2.2.2 on 2019-06-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(blank=True, max_length=64, verbose_name='机柜名称')),
                ('cabinet_code', models.CharField(blank=True, max_length=64, verbose_name='机柜编号')),
                ('room_id', models.IntegerField(blank=True, verbose_name='机房id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='设备名称')),
                ('device_type', models.CharField(blank=True, choices=[('storage', '存储设备'), ('safe', '安全设备')], max_length=32, verbose_name='设备类型')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='型号')),
                ('hardware', models.TextField(blank=True, null=True, verbose_name='硬件信息')),
                ('cabinet_id', models.IntegerField(blank=True, verbose_name='机柜id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='MachineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='机房名称')),
                ('room_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房编号')),
                ('region_id', models.IntegerField(blank=True, verbose_name='区域id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='区域')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
        ),
    ]
